version: '3.3'

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=store-api
      - POSTGRES_USER=adrian
      - POSTGRES_PASSWORD=1143412278
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
